name: retryable
description: make operation retryable.
version: 1.0.1
homepage: https://github.com/neutronstarer/retryable_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cancelable: ^1.0.2

dev_dependencies:
  test: ^1.0.0